exclude:
- "*.rb"
- "*.gemspec"
- "*.php"
- "*.sh"
- "*.csv"
- "*.sfd"
- "*.ai"
- "*.psd"
- "*.sketch"
- "*.yml"
- "*.lock"
- "*.log"
- "/css/*.md"
- "/js/*.md"
- "/img/*.md"
- "/fonts/*.md"
- "/js/*.json"
- "/css/*.json"
- "/img/*.json"
- "/js/*.html"
- Gemfile
- node_modules/
- docs
- palette.xml
- postcss.config.js
- postcss.config.json
- README.md
- LICENSE
- "*.config.js"
- "/img/octicons/test"
- "/img/octicons/*.js"
- "/img/octicons/*.md"
- "/img/octicons/LICENSE"
- "/img/octicons/lib/*.css"
- "/img/octicons/lib/octicons_gem"
- "/img/octicons/lib/octicons_node"
- "/img/octicons/lib/octicons_helper"
- "/img/octicons/lib/jekyll-octicons"
- "/img/octicons/script"
- "/img/adwaita-icons/docs"
- "/img/adwaita-icons/LICENSE"
- "css/core-css/docs"
- "css/normalize/*.html"
- "js/std-js/docs"
- "js/std-js/test"
